export const SCENES = {
  makeup: { id: "makeup", title: "公主换装化妆屋" },
  market: { id: "market", title: "蜜糖超市" },
  home: { id: "home", title: "温馨客厅" },
  kitchen: { id: "kitchen", title: "家庭厨房" },
  dining: { id: "dining", title: "温馨餐厅" },
};

export const COLORS = {
  skin: 0xf2c4a0,
  hair: 0x5a3a28,
  floor: 0xe8d4c4,
  wall: 0xfff0f5,
  coral: 0xef6b8a,
  wood: 0xc48a5a,
  woodDark: 0x8a5a38,
  metal: 0xb0c0d0,
  white: 0xffffff,
  green: 0x6ecf7a,
};

export const MARKET_GOODS = {
  drinks: [
    { id: "juice", name: "果汁", icon: "果汁", price: 8, tag: "drink", color: "#ffb347" },
    { id: "milk", name: "牛奶", icon: "牛奶", price: 7, tag: "drink", color: "#f5f5f5" },
    { id: "soda", name: "汽水", icon: "汽水", price: 6, tag: "drink", color: "#7ec8ff" },
  ],
  veg: [
    { id: "tomato", name: "番茄", icon: "茄", price: 4, tag: "veg", color: "#ff6b5a" },
    { id: "carrot", name: "胡萝卜", icon: "萝", price: 3, tag: "veg", color: "#ff8f40" },
    { id: "broccoli", name: "西兰花", icon: "兰", price: 5, tag: "veg", color: "#4aaa50" },
    { id: "cabbage", name: "白菜", icon: "白", price: 3, tag: "veg", color: "#d8f0c8" },
    { id: "potato", name: "土豆", icon: "薯", price: 3, tag: "veg", color: "#d4b896" },
    { id: "eggplant", name: "茄子", icon: "茄", price: 4, tag: "veg", color: "#7a4a9a" },
    { id: "pepper", name: "青椒", icon: "椒", price: 3, tag: "veg", color: "#3aaa40" },
    { id: "onion", name: "洋葱", icon: "葱", price: 3, tag: "veg", color: "#e8c8a0" },
    { id: "cucumber", name: "黄瓜", icon: "瓜", price: 3, tag: "veg", color: "#6ecf7a" },
    { id: "spinach", name: "菠菜", icon: "菠", price: 4, tag: "veg", color: "#2e8a40" },
    { id: "corn", name: "玉米", icon: "玉", price: 4, tag: "veg", color: "#ffe066" },
    { id: "mushroom", name: "口蘑", icon: "菇", price: 6, tag: "veg", color: "#c8b090" },
  ],
  daily: [
    { id: "rice", name: "大米", icon: "米", price: 12, tag: "rice", color: "#f5f0e0" },
    { id: "oil", name: "食用油", icon: "油", price: 15, tag: "oil", color: "#f0d060" },
    { id: "flour", name: "面粉", icon: "粉", price: 8, tag: "flour", color: "#fff8e8" },
    { id: "egg", name: "鸡蛋", icon: "蛋", price: 6, tag: "egg", color: "#ffe8b0" },
    { id: "tofu", name: "豆腐", icon: "腐", price: 5, tag: "tofu", color: "#f5f0e8" },
    { id: "noodle", name: "挂面", icon: "面", price: 7, tag: "noodle", color: "#f0e0c0" },
    { id: "chicken", name: "鸡肉", icon: "鸡", price: 14, tag: "meat", color: "#f0c0a8" },
    { id: "pork", name: "猪肉", icon: "肉", price: 16, tag: "meat", color: "#e89898" },
    { id: "beef", name: "牛肉", icon: "牛", price: 20, tag: "meat", color: "#c07060" },
    { id: "shrimp", name: "虾仁", icon: "虾", price: 18, tag: "seafood", color: "#ffb0b8" },
    { id: "cheese", name: "芝士", icon: "酪", price: 12, tag: "dairy", color: "#ffe08a" },
  ],
  snack: [
    { id: "chips", name: "薯片", icon: "薯", price: 8, tag: "snack", color: "#ffe08a" },
    { id: "bread", name: "面包胚", icon: "包", price: 6, tag: "flour", color: "#e8c898" },
  ],
  toys: [
    { id: "blocks", name: "积木", icon: "积", price: 18, tag: "toy", color: "#ff6b8a" },
    { id: "doll", name: "布娃娃", icon: "娃", price: 22, tag: "toy", color: "#ffb0c8" },
    { id: "toyCar", name: "小汽车", icon: "车", price: 16, tag: "toy", color: "#7ec8ff" },
    { id: "ball", name: "皮球", icon: "球", price: 12, tag: "toy", color: "#ffe08a" },
  ],
  household: [
    { id: "tissue", name: "纸巾", icon: "纸", price: 8, tag: "house", color: "#fff8f0" },
    { id: "soap", name: "香皂", icon: "皂", price: 6, tag: "house", color: "#ffb0c8" },
    { id: "shampoo", name: "洗发水", icon: "发", price: 15, tag: "house", color: "#c9a0e0" },
    { id: "toothbrush", name: "牙刷", icon: "刷", price: 5, tag: "house", color: "#7ec8ff" },
    { id: "towel", name: "毛巾", icon: "巾", price: 10, tag: "house", color: "#6ecf7a" },
  ],
  fruit: [
    { id: "apple", name: "苹果", icon: "果", price: 5, tag: "fruit", color: "#ef6b6a" },
    { id: "banana", name: "香蕉", icon: "蕉", price: 4, tag: "fruit", color: "#ffe066" },
    { id: "orange", name: "橙子", icon: "橙", price: 5, tag: "fruit", color: "#ff9f40" },
    { id: "grape", name: "葡萄", icon: "葡", price: 8, tag: "fruit", color: "#9b6ecf" },
  ],
};

/** 全部商品扁平表（按 id 查） */
export const ALL_GOODS = Object.values(MARKET_GOODS).flat();

/**
 * 菜谱：成品样式 + 材料清单
 * station: stove | rice | oven
 * ingredients[].needWash — 蔬菜需先洗净
 */
/** 预览色块快捷生成 */
const blob = (color, x, y, w, h, r = 40) => ({ color, x, y, w, h, r });

const FOOD_TINT = {
  chicken: "#f0c0a8",
  pork: "#e89898",
  beef: "#c07060",
  shrimp: "#ffb0b8",
  egg: "#ffe08a",
  cheese: "#ffe08a",
  oil: "#f0d060",
  noodle: "#f0e0c0",
  tomato: "#ff6b4a",
  pepper: "#3aaa40",
  potato: "#d4b896",
  carrot: "#ff8f40",
  onion: "#e8c8a0",
  cabbage: "#d8f0c8",
  broccoli: "#4aaa50",
  eggplant: "#7a4a9a",
  cucumber: "#6ecf7a",
  spinach: "#2e8a40",
  mushroom: "#c8b090",
  corn: "#ffe066",
  tofu: "#f5f0e8",
};

/** 灶台菜快捷生成（肉菜 / 面食批量用） */
function mkCook(id, name, icon, ingredientIds, opts = {}) {
  const wash = new Set(["tomato", "pepper", "potato", "carrot", "onion", "cabbage", "broccoli", "eggplant", "cucumber", "spinach", "mushroom", "corn"]);
  const names = {
    chicken: "鸡肉",
    pork: "猪肉",
    beef: "牛肉",
    shrimp: "虾仁",
    egg: "鸡蛋",
    cheese: "芝士",
    oil: "食用油",
    milk: "牛奶",
    juice: "果汁",
    noodle: "挂面",
    tomato: "番茄",
    pepper: "青椒",
    potato: "土豆",
    carrot: "胡萝卜",
    onion: "洋葱",
    cabbage: "白菜",
    broccoli: "西兰花",
    eggplant: "茄子",
    cucumber: "黄瓜",
    spinach: "菠菜",
    mushroom: "口蘑",
    corn: "玉米",
    tofu: "豆腐",
  };
  const ids = ingredientIds.includes("oil") || opts.noOil ? ingredientIds : [...ingredientIds, "oil"];
  const foods = ids
    .filter((x) => x !== "oil")
    .slice(0, 3)
    .map((fid, i) => blob(FOOD_TINT[fid] || "#e8d0a0", 26 + i * 16, 34 + (i % 2) * 6, 34 - i * 2, 26 - i, i === 0 ? 40 : 45));
  const station = opts.station || "stove";
  let category = opts.category;
  if (!category) {
    if (ids.includes("noodle") || name.includes("面") || name.includes("饭") || name.includes("面包")) category = "staple";
    else if (name.includes("凉") || name.includes("凉拌")) category = "cold";
    else if (name.includes("奶") && (name.includes("粥") || name.includes("饮"))) category = "drink";
    else if (name.includes("汤") || name.includes("炖") || name.includes("粥") || name.includes("牛腩")) category = "soup";
    else if (station === "rice" || station === "oven") category = "staple";
    else category = "stirfry";
  }
  return {
    id,
    name,
    dish: name,
    icon,
    category,
    station,
    power: opts.power || "stove",
    needHood: opts.needHood !== false,
    time: opts.time || 3000,
    vesselDefault: opts.vessel || "plate",
    desc: opts.desc || "家常好味道",
    ingredients: ids.map((fid) => ({
      id: fid,
      name: names[fid] || fid,
      ...(wash.has(fid) ? { needWash: true } : {}),
    })),
    preview: {
      plate: opts.vessel === "bowl" ? "#f0e8e0" : "#faf6f0",
      ...(opts.vessel === "bowl" ? { bowl: true } : {}),
      foods,
    },
  };
}

/** 菜谱分类（厨房菜单 Tab） */
export const DISH_CATEGORIES = [
  { id: "all", name: "全部" },
  { id: "stirfry", name: "炒菜" },
  { id: "staple", name: "主食" },
  { id: "soup", name: "汤类" },
  { id: "cold", name: "凉菜" },
  { id: "drink", name: "饮料" },
];

export function getDishCategory(recipe) {
  if (!recipe) return "stirfry";
  if (recipe.category) return recipe.category;
  const n = recipe.name || "";
  const ids = (recipe.ingredients || []).map((i) => i.id);
  if (ids.includes("noodle") || n.includes("面") || n.includes("饭") || n.includes("面包") || recipe.station === "rice") {
    return "staple";
  }
  if (n.includes("凉") || n.includes("凉拌")) return "cold";
  if ((n.includes("奶") || n.includes("果汁")) && (n.includes("粥") || n.includes("饮") || ids.includes("milk") || ids.includes("juice"))) {
    return "drink";
  }
  if (n.includes("汤") || n.includes("炖") || n.includes("粥") || n.includes("牛腩")) return "soup";
  if (recipe.station === "oven") return "staple";
  return "stirfry";
}

/** 五十道新增肉菜（鸡/猪/牛/虾） */
const EXTRA_MEAT_DISHES = [
  mkCook("porkPepper", "青椒炒肉", "🫑", ["pork", "pepper"], { desc: "下饭经典" }),
  mkCook("porkTomato", "番茄炒肉", "🍅", ["pork", "tomato"], { desc: "酸甜开胃" }),
  mkCook("porkPotato", "土豆烧肉", "🥔", ["pork", "potato"], { vessel: "bowl", time: 3400, desc: "软糯入味" }),
  mkCook("porkCarrot", "胡萝卜炖肉", "🥕", ["pork", "carrot"], { vessel: "bowl", time: 3400, desc: "暖胃家常" }),
  mkCook("porkOnion", "洋葱炒肉丝", "🧅", ["pork", "onion"], { desc: "甜香扑鼻" }),
  mkCook("porkBroccoli", "西兰花炒肉", "🥦", ["pork", "broccoli"], { desc: "荤素搭配" }),
  mkCook("porkCabbageStir", "白菜炒肉丝", "🥬", ["pork", "cabbage"], { desc: "清爽不腻" }),
  mkCook("porkEggplant", "茄子烧肉", "🍆", ["pork", "eggplant"], { vessel: "bowl", time: 3200, desc: "软烂入味" }),
  mkCook("porkCucumber", "黄瓜炒肉", "🥒", ["pork", "cucumber"], { desc: "脆嫩爽口" }),
  mkCook("porkSpinach", "菠菜炒肉", "🥬", ["pork", "spinach"], { desc: "补铁下饭" }),
  mkCook("porkMushroom", "口蘑炒肉", "🍄", ["pork", "mushroom"], { desc: "菌香浓郁" }),
  mkCook("porkCorn", "玉米炒肉", "🌽", ["pork", "corn"], { desc: "甜香一口" }),
  mkCook("porkPepperOnion", "回锅肉", "🥓", ["pork", "pepper", "onion"], { time: 3200, desc: "肥而不腻" }),
  mkCook("porkFishFlavor", "鱼香肉丝", "🥢", ["pork", "carrot", "pepper"], { time: 3200, desc: "酸甜微辣" }),
  mkCook("porkMooShu", "木须肉", "🥚", ["pork", "egg", "mushroom"], { desc: "软滑鲜香" }),
  mkCook("porkSweetSour", "糖醋里脊", "🍬", ["pork", "tomato"], { time: 3200, desc: "酸甜酥香" }),
  mkCook("porkBraised", "红烧肉", "🍖", ["pork", "onion"], { vessel: "bowl", time: 3600, desc: "色泽红亮" }),
  mkCook("porkEggPatty", "猪肉煎蛋", "🍳", ["pork", "egg"], { desc: "香煎金黄" }),
  mkCook("porkCheese", "芝士烤肉", "🧀", ["pork", "cheese"], { station: "oven", power: "oven", needHood: false, desc: "拉丝浓香" }),
  mkCook("porkTofu", "肉末豆腐", "🧈", ["pork", "tofu"], { vessel: "bowl", desc: "嫩滑入味" }),
  mkCook("beefPepper", "青椒牛肉丝", "🫑", ["beef", "pepper"], { desc: "嫩滑劲道" }),
  mkCook("beefTomato", "番茄牛腩", "🍅", ["beef", "tomato"], { vessel: "bowl", time: 3600, desc: "汤浓肉烂" }),
  mkCook("beefPotato", "土豆烧牛肉", "🥔", ["beef", "potato"], { vessel: "bowl", time: 3600, desc: "硬菜一锅" }),
  mkCook("beefCarrot", "胡萝卜炖牛腩", "🥕", ["beef", "carrot"], { vessel: "bowl", time: 3600, desc: "暖乎乎" }),
  mkCook("beefOnion", "洋葱炒牛肉", "🧅", ["beef", "onion"], { desc: "快手香嫩" }),
  mkCook("beefBroccoli", "西兰花炒牛肉", "🥦", ["beef", "broccoli"], { desc: "营养均衡" }),
  mkCook("beefMushroom", "口蘑炒牛肉", "🍄", ["beef", "mushroom"], { desc: "西式家常" }),
  mkCook("beefCabbage", "白菜炖牛肉", "🥬", ["beef", "cabbage"], { vessel: "bowl", time: 3400, desc: "软烂入味" }),
  mkCook("beefEggplant", "茄子牛肉", "🍆", ["beef", "eggplant"], { vessel: "bowl", time: 3300, desc: "酱香浓郁" }),
  mkCook("beefSpinach", "菠菜牛肉", "🥬", ["beef", "spinach"], { desc: "清香不腻" }),
  mkCook("beefCorn", "玉米炒牛肉", "🌽", ["beef", "corn"], { desc: "甜香开胃" }),
  mkCook("beefCucumber", "黄瓜炒牛肉", "🥒", ["beef", "cucumber"], { desc: "清脆爽口" }),
  mkCook("beefPepperOnion", "小炒黄牛肉", "🥩", ["beef", "pepper", "onion"], { time: 3200, desc: "火候刚好" }),
  mkCook("beefEgg", "滑蛋牛肉", "🥚", ["beef", "egg"], { desc: "嫩滑下饭" }),
  mkCook("beefCheese", "芝士烤牛肉", "🧀", ["beef", "cheese"], { station: "oven", power: "oven", needHood: false, desc: "聚会硬菜" }),
  mkCook("chickenPepper", "辣子鸡", "🌶️", ["chicken", "pepper"], { time: 3200, desc: "干香过瘾" }),
  mkCook("chickenTomato", "番茄炒鸡", "🍅", ["chicken", "tomato"], { desc: "酸甜鲜嫩" }),
  mkCook("chickenPotato", "土豆炖鸡", "🥔", ["chicken", "potato"], { vessel: "bowl", time: 3400, desc: "一锅暖心" }),
  mkCook("chickenCarrot", "胡萝卜炒鸡", "🥕", ["chicken", "carrot"], { desc: "家常快手" }),
  mkCook("chickenOnion", "洋葱炒鸡", "🧅", ["chicken", "onion"], { desc: "甜香扑鼻" }),
  mkCook("chickenCabbage", "白菜炒鸡", "🥬", ["chicken", "cabbage"], { desc: "清淡鲜美" }),
  mkCook("chickenCorn", "玉米炒鸡", "🌽", ["chicken", "corn"], { desc: "金黄香甜" }),
  mkCook("chickenEggplant", "茄子烧鸡", "🍆", ["chicken", "eggplant"], { vessel: "bowl", time: 3200, desc: "软糯入味" }),
  mkCook("chickenSpinach", "菠菜炒鸡", "🥬", ["chicken", "spinach"], { desc: "绿意满盘" }),
  mkCook("chickenCucumber", "黄瓜炒鸡", "🥒", ["chicken", "cucumber"], { desc: "清爽不腻" }),
  mkCook("chickenBroccoliStir", "西兰花炒鸡", "🥦", ["chicken", "broccoli"], { desc: "健康下饭" }),
  mkCook("chickenKungPao", "宫保鸡丁", "🥜", ["chicken", "pepper", "cucumber"], { time: 3200, desc: "微辣鲜香" }),
  mkCook("chickenEgg", "滑蛋鸡片", "🥚", ["chicken", "egg"], { desc: "嫩滑可口" }),
  mkCook("chickenCheese", "芝士烤鸡", "🧀", ["chicken", "cheese"], { station: "oven", power: "oven", needHood: false, desc: "外焦里嫩" }),
  mkCook("chickenTofu", "鸡丁豆腐", "🧈", ["chicken", "tofu"], { vessel: "bowl", desc: "鲜嫩一碗" }),
  mkCook("shrimpBroccoli", "虾仁西兰花", "🥦", ["shrimp", "broccoli"], { desc: "清鲜营养" }),
  mkCook("shrimpCucumber", "黄瓜炒虾仁", "🥒", ["shrimp", "cucumber"], { desc: "脆嫩爽口" }),
  mkCook("shrimpTomato", "番茄炒虾", "🍅", ["shrimp", "tomato"], { desc: "酸甜鲜美" }),
  mkCook("shrimpPepper", "青椒虾仁", "🫑", ["shrimp", "pepper"], { desc: "快手下饭" }),
  mkCook("shrimpMushroom", "口蘑虾仁", "🍄", ["shrimp", "mushroom"], { desc: "菌香衬虾" }),
  mkCook("shrimpSpinach", "菠菜虾仁", "🥬", ["shrimp", "spinach"], { desc: "清香不腻" }),
  mkCook("shrimpCorn", "玉米虾仁", "🌽", ["shrimp", "corn"], { desc: "甜鲜一口" }),
  mkCook("shrimpOnion", "洋葱炒虾", "🧅", ["shrimp", "onion"], { desc: "香气十足" }),
  mkCook("shrimpEggplant", "茄子虾仁", "🍆", ["shrimp", "eggplant"], { desc: "软糯鲜香" }),
  mkCook("shrimpCarrot", "胡萝卜炒虾", "🥕", ["shrimp", "carrot"], { desc: "色彩好看" }),
  mkCook("shrimpCabbage", "白菜炒虾", "🥬", ["shrimp", "cabbage"], { desc: "清淡鲜甜" }),
  mkCook("shrimpPotato", "土豆虾仁", "🥔", ["shrimp", "potato"], { desc: "软糯搭配" }),
  mkCook("shrimpCheeseBake2", "黄油烤虾", "🧈", ["shrimp", "cheese", "onion"], {
    station: "oven",
    power: "oven",
    needHood: false,
    time: 3200,
    desc: "香气四溢",
  }),
].slice(0, 50);

/** 汤面 / 牛肉面 / 番茄面 / 蔬菜面等 */
const EXTRA_NOODLE_DISHES = [
  mkCook("soupNoodle", "汤面", "🍜", ["noodle"], { vessel: "bowl", time: 2600, desc: "清汤热乎乎", needHood: true, category: "staple" }),
  mkCook("beefNoodle", "牛肉面", "🍜", ["noodle", "beef", "onion"], { vessel: "bowl", time: 3400, desc: "汤浓肉香", category: "staple" }),
  mkCook("tomatoSoupNoodle", "番茄面", "🍅", ["noodle", "tomato", "egg"], { vessel: "bowl", time: 3000, desc: "酸甜一碗面", category: "staple" }),
  mkCook("vegNoodle", "蔬菜面", "🥬", ["noodle", "broccoli", "carrot"], { vessel: "bowl", time: 3000, desc: "清爽营养", category: "staple" }),
  mkCook("chickenNoodle", "鸡肉面", "🍗", ["noodle", "chicken"], { vessel: "bowl", time: 3000, desc: "鲜香暖胃", category: "staple" }),
  mkCook("porkNoodle", "肉丝面", "🥓", ["noodle", "pork"], { vessel: "bowl", time: 3000, desc: "经典早餐面", category: "staple" }),
  mkCook("shrimpNoodle", "虾仁面", "🦐", ["noodle", "shrimp"], { vessel: "bowl", time: 3000, desc: "鲜香一碗", category: "staple" }),
  mkCook("spinachNoodle", "菠菜面", "🥬", ["noodle", "spinach", "egg"], { vessel: "bowl", time: 2800, desc: "绿意满碗", category: "staple" }),
  mkCook("mushroomNoodle", "口蘑面", "🍄", ["noodle", "mushroom"], { vessel: "bowl", time: 2800, desc: "菌香汤面", category: "staple" }),
  mkCook("pepperNoodle", "青椒肉丝面", "🫑", ["noodle", "pork", "pepper"], { vessel: "bowl", time: 3000, desc: "干香过瘾", category: "staple" }),
  mkCook("hotMilk", "热牛奶", "🥛", ["milk"], { vessel: "bowl", time: 2000, needHood: false, noOil: true, category: "drink", desc: "暖暖一杯" }),
  mkCook("fruitJuiceDrink", "鲜榨果汁", "🧃", ["juice"], { vessel: "bowl", time: 1800, needHood: false, noOil: true, category: "drink", desc: "清爽解渴" }),
];

export const DISH_RECIPES = [
  {
    id: "tomatoEgg",
    name: "西红柿炒鸡蛋",
    dish: "西红柿炒鸡蛋",
    icon: "🍳",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2800,
    vesselDefault: "plate",
    desc: "家常经典，酸甜滑嫩",
    ingredients: [
      { id: "tomato", name: "番茄", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#ff6b4a", 28, 32, 44, 28), blob("#ffe08a", 48, 38, 36, 22), blob("#ff8f60", 36, 48, 30, 18, 50)] },
  },
  {
    id: "stirBroccoli",
    name: "清炒西兰花",
    dish: "清炒西兰花",
    icon: "🥦",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2400,
    vesselDefault: "plate",
    desc: "清脆鲜绿",
    ingredients: [
      { id: "broccoli", name: "西兰花", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#4aaa50", 34, 34, 38, 38, 50), blob("#3ecf6a", 48, 40, 28, 28, 50)] },
  },
  {
    id: "stirCabbage",
    name: "素炒白菜",
    dish: "素炒白菜",
    icon: "🥬",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2200,
    vesselDefault: "plate",
    desc: "清淡爽口",
    ingredients: [
      { id: "cabbage", name: "白菜", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#d8f0c8", 30, 36, 46, 30), blob("#c0dca8", 44, 44, 34, 24)] },
  },
  {
    id: "carrotEgg",
    name: "胡萝卜炒蛋",
    dish: "胡萝卜炒蛋",
    icon: "🥕",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2600,
    vesselDefault: "plate",
    desc: "香甜营养",
    ingredients: [
      { id: "carrot", name: "胡萝卜", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#ff8f40", 32, 36, 40, 26), blob("#ffe08a", 48, 42, 32, 22)] },
  },
  {
    id: "potatoStir",
    name: "清炒土豆丝",
    dish: "清炒土豆丝",
    icon: "🥔",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2600,
    vesselDefault: "plate",
    desc: "脆嫩微辣风",
    ingredients: [
      { id: "potato", name: "土豆", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#e8d0a8", 28, 36, 48, 28), blob("#d4b896", 40, 46, 36, 20)] },
  },
  {
    id: "eggplantGarlic",
    name: "蒜香茄子",
    dish: "蒜香茄子",
    icon: "🍆",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2800,
    vesselDefault: "plate",
    desc: "软糯入味",
    ingredients: [
      { id: "eggplant", name: "茄子", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#7a4a9a", 30, 34, 42, 32), blob("#5a3070", 48, 44, 28, 22)] },
  },
  {
    id: "pepperEgg",
    name: "青椒炒蛋",
    dish: "青椒炒蛋",
    icon: "🫑",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2500,
    vesselDefault: "plate",
    desc: "下饭快手菜",
    ingredients: [
      { id: "pepper", name: "青椒", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#3aaa40", 30, 34, 36, 28), blob("#ffe08a", 50, 40, 32, 24)] },
  },
  {
    id: "onionEgg",
    name: "洋葱炒蛋",
    dish: "洋葱炒蛋",
    icon: "🧅",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2500,
    vesselDefault: "plate",
    desc: "甜香软滑",
    ingredients: [
      { id: "onion", name: "洋葱", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#e8c8a0", 30, 36, 40, 26), blob("#ffe08a", 48, 42, 34, 22)] },
  },
  {
    id: "cucumberSalad",
    name: "凉拌黄瓜",
    dish: "凉拌黄瓜",
    icon: "🥒",
    station: "stove",
    power: "stove",
    needHood: false,
    time: 1800,
    vesselDefault: "plate",
    desc: "清爽开胃，不用开火也能做",
    ingredients: [{ id: "cucumber", name: "黄瓜", needWash: true }],
    preview: { plate: "#faf6f0", foods: [blob("#6ecf7a", 26, 38, 50, 22), blob("#4aaa50", 40, 48, 34, 16)] },
  },
  {
    id: "spinachEgg",
    name: "菠菜炒蛋",
    dish: "菠菜炒蛋",
    icon: "🥬",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2400,
    vesselDefault: "plate",
    desc: "绿意满满",
    ingredients: [
      { id: "spinach", name: "菠菜", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#2e8a40", 28, 34, 40, 30), blob("#ffe08a", 50, 42, 30, 22)] },
  },
  {
    id: "cornEgg",
    name: "玉米炒蛋",
    dish: "玉米炒蛋",
    icon: "🌽",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2400,
    vesselDefault: "plate",
    desc: "金黄甜香",
    ingredients: [
      { id: "corn", name: "玉米", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#ffe066", 30, 36, 38, 26), blob("#ffe08a", 50, 42, 32, 22)] },
  },
  {
    id: "mushroomStir",
    name: "清炒口蘑",
    dish: "清炒口蘑",
    icon: "🍄",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2400,
    vesselDefault: "plate",
    desc: "菌香鲜美",
    ingredients: [
      { id: "mushroom", name: "口蘑", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#c8b090", 32, 34, 36, 32, 50), blob("#a89070", 50, 44, 28, 24, 50)] },
  },
  {
    id: "tofuHome",
    name: "家常豆腐",
    dish: "家常豆腐",
    icon: "🧈",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2700,
    vesselDefault: "plate",
    desc: "外焦里嫩",
    ingredients: [
      { id: "tofu", name: "豆腐" },
      { id: "pepper", name: "青椒", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#f5f0e8", 28, 36, 36, 28), blob("#3aaa40", 52, 40, 26, 24)] },
  },
  {
    id: "chickenMushroom",
    name: "香菇滑鸡",
    dish: "香菇滑鸡",
    icon: "🍗",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 3200,
    vesselDefault: "plate",
    desc: "鲜嫩下饭",
    ingredients: [
      { id: "chicken", name: "鸡肉" },
      { id: "mushroom", name: "口蘑", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#f0c0a8", 28, 34, 40, 28), blob("#c8b090", 50, 42, 30, 24, 50)] },
  },
  {
    id: "shrimpEgg",
    name: "虾仁炒蛋",
    dish: "虾仁炒蛋",
    icon: "🦐",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2800,
    vesselDefault: "plate",
    desc: "鲜香软滑",
    ingredients: [
      { id: "shrimp", name: "虾仁" },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#ffb0b8", 28, 36, 34, 26), blob("#ffe08a", 50, 40, 34, 24)] },
  },
  {
    id: "porkCabbage",
    name: "猪肉炖白菜",
    dish: "猪肉炖白菜",
    icon: "🥘",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 3400,
    vesselDefault: "bowl",
    desc: "暖乎乎一大碗",
    ingredients: [
      { id: "pork", name: "猪肉" },
      { id: "cabbage", name: "白菜", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#e89898", 30, 34, 36, 28), blob("#d8f0c8", 48, 42, 32, 24)] },
  },
  {
    id: "tomatoPotato",
    name: "番茄炖土豆",
    dish: "番茄炖土豆",
    icon: "🍲",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 3000,
    vesselDefault: "bowl",
    desc: "酸甜软糯",
    ingredients: [
      { id: "tomato", name: "番茄", needWash: true },
      { id: "potato", name: "土豆", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#ff6b4a", 28, 34, 38, 28), blob("#d4b896", 50, 42, 30, 24)] },
  },
  {
    id: "vegMix",
    name: "素什锦",
    dish: "素什锦",
    icon: "🥗",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2800,
    vesselDefault: "plate",
    desc: "五颜六色一盘鲜",
    ingredients: [
      { id: "carrot", name: "胡萝卜", needWash: true },
      { id: "broccoli", name: "西兰花", needWash: true },
      { id: "mushroom", name: "口蘑", needWash: true },
      { id: "oil", name: "食用油" },
    ],
    preview: {
      plate: "#faf6f0",
      foods: [blob("#ff8f40", 24, 36, 28, 24), blob("#4aaa50", 44, 32, 28, 28, 50), blob("#c8b090", 58, 44, 24, 22, 50)],
    },
  },
  {
    id: "tomatoNoodle",
    name: "番茄炒面",
    dish: "番茄炒面",
    icon: "🍜",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 3000,
    vesselDefault: "bowl",
    desc: "简单解馋",
    ingredients: [
      { id: "noodle", name: "挂面" },
      { id: "tomato", name: "番茄", needWash: true },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#e8d0a0", 28, 36, 48, 28), blob("#ff6b4a", 40, 44, 30, 20)] },
  },
  {
    id: "eggNoodle",
    name: "鸡蛋挂面",
    dish: "鸡蛋挂面",
    icon: "🍝",
    station: "stove",
    power: "stove",
    needHood: true,
    time: 2800,
    vesselDefault: "bowl",
    desc: "一碗热汤面",
    ingredients: [
      { id: "noodle", name: "挂面" },
      { id: "egg", name: "鸡蛋" },
      { id: "oil", name: "食用油" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#f0e0c0", 28, 36, 48, 30), blob("#ffe08a", 46, 42, 28, 20)] },
  },
  {
    id: "porridge",
    name: "白粥",
    dish: "白粥",
    icon: "🥣",
    station: "stove",
    power: "stove",
    needHood: false,
    time: 2600,
    vesselDefault: "bowl",
    desc: "暖暖一碗粥",
    ingredients: [{ id: "rice", name: "大米" }],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#f5f0e0", 28, 36, 48, 32, 50)] },
  },
  {
    id: "milkPorridge",
    name: "牛奶粥",
    dish: "牛奶粥",
    icon: "🥛",
    station: "stove",
    power: "stove",
    needHood: false,
    time: 2800,
    vesselDefault: "bowl",
    desc: "香浓好喝",
    ingredients: [
      { id: "rice", name: "大米" },
      { id: "milk", name: "牛奶" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#fff8f0", 28, 36, 48, 32, 50)] },
  },
  {
    id: "steamRice",
    name: "蒸米饭",
    dish: "米饭",
    icon: "🍚",
    station: "rice",
    power: "rice",
    time: 2800,
    vesselDefault: "bowl",
    desc: "粒粒饱满",
    ingredients: [{ id: "rice", name: "大米" }],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#fffaf0", 30, 34, 44, 36, 50)] },
  },
  {
    id: "eggPorridge",
    name: "鸡蛋粥",
    dish: "鸡蛋粥",
    icon: "🍳",
    station: "rice",
    power: "rice",
    time: 3000,
    vesselDefault: "bowl",
    desc: "软糯养人",
    ingredients: [
      { id: "rice", name: "大米" },
      { id: "egg", name: "鸡蛋" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#f5f0e0", 28, 34, 44, 32, 50), blob("#ffe08a", 48, 44, 26, 18)] },
  },
  {
    id: "cornRice",
    name: "玉米饭",
    dish: "玉米饭",
    icon: "🌽",
    station: "rice",
    power: "rice",
    time: 3000,
    vesselDefault: "bowl",
    desc: "粒粒带甜",
    ingredients: [
      { id: "rice", name: "大米" },
      { id: "corn", name: "玉米", needWash: true },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#fffaf0", 28, 34, 40, 32, 50), blob("#ffe066", 50, 42, 26, 22)] },
  },
  {
    id: "vegRice",
    name: "蔬菜焖饭",
    dish: "蔬菜焖饭",
    icon: "🍱",
    station: "rice",
    power: "rice",
    time: 3200,
    vesselDefault: "bowl",
    desc: "一锅出饭菜",
    ingredients: [
      { id: "rice", name: "大米" },
      { id: "carrot", name: "胡萝卜", needWash: true },
      { id: "broccoli", name: "西兰花", needWash: true },
    ],
    preview: {
      plate: "#f0e8e0",
      bowl: true,
      foods: [blob("#fffaf0", 26, 34, 36, 30, 50), blob("#ff8f40", 48, 38, 22, 20), blob("#4aaa50", 54, 48, 20, 18, 50)],
    },
  },
  {
    id: "toastBread",
    name: "烤面包",
    dish: "烤面包",
    icon: "🍞",
    station: "oven",
    power: "oven",
    time: 3000,
    vesselDefault: "plate",
    desc: "外焦里软",
    ingredients: [{ id: "flour", name: "面粉" }],
    preview: { plate: "#faf6f0", foods: [blob("#e8c898", 28, 40, 48, 24, 20), blob("#c89868", 32, 36, 40, 10, 10)] },
  },
  {
    id: "eggCustardBake",
    name: "烤蛋奶",
    dish: "烤蛋奶",
    icon: "🍮",
    station: "oven",
    power: "oven",
    time: 3200,
    vesselDefault: "bowl",
    desc: "香甜嫩滑",
    ingredients: [
      { id: "egg", name: "鸡蛋" },
      { id: "milk", name: "牛奶" },
      { id: "flour", name: "面粉" },
    ],
    preview: { plate: "#f0e8e0", bowl: true, foods: [blob("#ffe8b0", 28, 36, 48, 30, 50)] },
  },
  {
    id: "bakedPotato",
    name: "烤土豆",
    dish: "烤土豆",
    icon: "🥔",
    station: "oven",
    power: "oven",
    time: 3200,
    vesselDefault: "plate",
    desc: "外皮酥香",
    ingredients: [{ id: "potato", name: "土豆", needWash: true }],
    preview: { plate: "#faf6f0", foods: [blob("#d4b896", 32, 36, 40, 32, 45), blob("#c4a070", 40, 32, 28, 14, 20)] },
  },
  {
    id: "cheeseBread",
    name: "芝士面包",
    dish: "芝士面包",
    icon: "🧀",
    station: "oven",
    power: "oven",
    time: 3000,
    vesselDefault: "plate",
    desc: "拉丝好滋味",
    ingredients: [
      { id: "bread", name: "面包胚" },
      { id: "cheese", name: "芝士" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#e8c898", 28, 40, 48, 24, 20), blob("#ffe08a", 34, 34, 36, 14, 30)] },
  },
  {
    id: "vegBake",
    name: "烤时蔬",
    dish: "烤时蔬",
    icon: "🥦",
    station: "oven",
    power: "oven",
    time: 3000,
    vesselDefault: "plate",
    desc: "健康低油",
    ingredients: [
      { id: "broccoli", name: "西兰花", needWash: true },
      { id: "carrot", name: "胡萝卜", needWash: true },
      { id: "potato", name: "土豆", needWash: true },
    ],
    preview: {
      plate: "#faf6f0",
      foods: [blob("#4aaa50", 24, 34, 28, 28, 50), blob("#ff8f40", 44, 38, 26, 22), blob("#d4b896", 58, 44, 24, 22, 45)],
    },
  },
  {
    id: "shrimpBake",
    name: "芝士烤虾",
    dish: "芝士烤虾",
    icon: "🦐",
    station: "oven",
    power: "oven",
    time: 3200,
    vesselDefault: "plate",
    desc: "聚会硬菜",
    ingredients: [
      { id: "shrimp", name: "虾仁" },
      { id: "cheese", name: "芝士" },
    ],
    preview: { plate: "#faf6f0", foods: [blob("#ffb0b8", 28, 36, 36, 26), blob("#ffe08a", 50, 40, 30, 22)] },
  },
  ...EXTRA_MEAT_DISHES,
  ...EXTRA_NOODLE_DISHES,
];

/** @deprecated 兼容旧 startCook(type) —— 映射到菜站默认菜 */
export const RECIPES = {
  stirfry: DISH_RECIPES.find((r) => r.id === "tomatoEgg"),
  rice: DISH_RECIPES.find((r) => r.id === "steamRice"),
  porridge: DISH_RECIPES.find((r) => r.id === "porridge"),
  bread: DISH_RECIPES.find((r) => r.id === "toastBread"),
};

export const MAKEUP = {
  modes: [
    { id: "makeup", name: "化妆台" },
    { id: "dress", name: "换装间" },
  ],
  makeupTabs: [
    { id: "lipstick", name: "口红" },
    { id: "blush", name: "腮红" },
    { id: "eyeshadow", name: "眼影" },
    { id: "faceShape", name: "脸型" },
    { id: "features", name: "五官" },
  ],
  dressTabs: [
    { id: "hairstyle", name: "发型" },
    { id: "hair", name: "发色" },
    { id: "top", name: "上衣" },
    { id: "bottom", name: "下装" },
    { id: "hat", name: "帽子" },
    { id: "jewelry", name: "首饰" },
    { id: "baby", name: "宝宝" },
    { id: "prop", name: "大道具" },
  ],
  tabs: [
    { id: "lipstick", name: "口红" },
    { id: "blush", name: "腮红" },
    { id: "eyeshadow", name: "眼影" },
    { id: "faceShape", name: "脸型" },
    { id: "features", name: "五官" },
    { id: "hairstyle", name: "发型" },
    { id: "hair", name: "发色" },
    { id: "top", name: "上衣" },
    { id: "bottom", name: "下装" },
    { id: "hat", name: "帽子" },
    { id: "jewelry", name: "首饰" },
    { id: "baby", name: "宝宝" },
    { id: "prop", name: "大道具" },
    { id: "bg", name: "背景" },
  ],
  faceShape: [
    { id: "faceRound", name: "圆脸", icon: "⭕", shape: "round", rx: 92, ry: 92, desc: "可爱圆脸" },
    { id: "faceOval", name: "鹅蛋脸", icon: "🥚", shape: "oval", rx: 82, ry: 98, desc: "经典鹅蛋" },
    { id: "faceHeart", name: "心形脸", icon: "💗", shape: "heart", rx: 88, ry: 94, desc: "上宽下尖" },
    { id: "faceSoft", name: "柔和脸", icon: "☁️", shape: "soft", rx: 90, ry: 88, desc: "软萌短脸" },
    { id: "faceLong", name: "瓜子脸", icon: "🌙", shape: "long", rx: 76, ry: 102, desc: "清秀瓜子" },
  ],
  features: [
    { id: "featSweet", name: "甜笑", icon: "😊", look: "sweet", eyeScale: 1, desc: "弯弯笑眼" },
    { id: "featCool", name: "酷感", icon: "😎", look: "cool", eyeScale: 0.92, desc: "细长眼型" },
    { id: "featShy", name: "害羞", icon: "🥺", look: "shy", eyeScale: 1.05, desc: "水汪汪" },
    { id: "featLively", name: "元气", icon: "😆", look: "lively", eyeScale: 1.08, desc: "大笑露齿" },
    { id: "featGentle", name: "温柔", icon: "😌", look: "gentle", eyeScale: 0.98, desc: "浅笑温柔" },
  ],
  hairstyle: [
    { id: "hsTwin", name: "双马尾", icon: "🎀", style: "twin", desc: "活泼双马尾" },
    { id: "hsPony", name: "高马尾", icon: "🏇", style: "pony", desc: "利落马尾" },
    { id: "hsBob", name: "齐肩短发", icon: "💇", style: "bob", desc: "清爽短发" },
    { id: "hsLong", name: "长直发", icon: "👩", style: "long", desc: "飘逸长发" },
    { id: "hsBun", name: "丸子头", icon: "🍡", style: "bun", desc: "可爱丸子" },
    { id: "hsWave", name: "大波浪", icon: "🌊", style: "wave", desc: "卷卷波浪" },
  ],
  lipstick: [
    { id: "lip1", name: "蜜桃嘟嘟", icon: "💄", color: "#FF7FA3", desc: "水润唇膏" },
    { id: "lip2", name: "樱桃甜心", icon: "💋", color: "#d4455a", desc: "丝绒口红" },
    { id: "lip3", name: "豆沙奶茶", icon: "🧋", color: "#b06070", desc: "哑光唇泥" },
    { id: "lip4", name: "珊瑚橘", icon: "🍊", color: "#ff7a5c", desc: "亮泽唇彩" },
    { id: "lip5", name: "玫瑰雾", icon: "🌹", color: "#c45a78", desc: "雾面唇釉" },
    { id: "lip6", name: "裸粉", icon: "🎀", color: "#e8a0b0", desc: "日常淡唇" },
    { id: "lip7", name: "正红色", icon: "❤️", color: "#e11d48", desc: "经典口红" },
    { id: "lip8", name: "葡萄紫", icon: "🍇", color: "#7c3a6a", desc: "复古唇膏" },
  ],
  blush: [
    { id: "blush1", name: "蜜桃腮红", icon: "🍑", color: "#FF8AA8", desc: "粉饼" },
    { id: "blush2", name: "珊瑚蜜", icon: "🪸", color: "#ff8a9a", desc: "液体腮红" },
    { id: "blush3", name: "自然好气色", icon: "☀️", color: "#f0a090", desc: "修容盘" },
    { id: "blush4", name: "草莓冰", icon: "🍓", color: "#ff6b8a", desc: "奶油腮红" },
    { id: "blush5", name: "杏子奶", icon: "🧁", color: "#f0b898", desc: "柔光粉" },
    { id: "blush6", name: "梅子色", icon: "💜", color: "#c08098", desc: "高级腮红" },
  ],
  eyeshadow: [
    { id: "eye1", name: "粉棕盘", icon: "👁️", color: "#FF9EC0", desc: "四色眼影" },
    { id: "eye2", name: "玫瑰盘", icon: "🌺", color: "#d07090", desc: "珠光眼影" },
    { id: "eye3", name: "大地盘", icon: "🍂", color: "#a87858", desc: "哑光眼影" },
    { id: "eye4", name: "香槟金", icon: "✨", color: "#e8c898", desc: "闪片眼影" },
    { id: "eye5", name: "莓果紫", icon: "💜", color: "#9a6a9a", desc: "烟熏眼影" },
    { id: "eye6", name: "海蓝石", icon: "💙", color: "#6a9ac8", desc: "冷调眼影" },
  ],
  hair: [
    { id: "hair1", name: "栗棕日常", icon: "👧", color: "#6B3F2A", desc: "自然棕" },
    { id: "hair2", name: "深褐夜色", icon: "💇", color: "#3a2820", desc: "深色染" },
    { id: "hair3", name: "蜜茶金", icon: "🍵", color: "#8a5a38", desc: "浅棕染" },
    { id: "hair4", name: "红酒棕", icon: "🍷", color: "#6a3040", desc: "酒红染" },
    { id: "hair5", name: "巧克力", icon: "🍫", color: "#4a3020", desc: "暖棕染" },
    { id: "hair6", name: "亚麻浅棕", icon: "🌾", color: "#a07850", desc: "日系染" },
    { id: "hair7", name: "樱花粉", icon: "🌸", color: "#e8a0b8", desc: "粉色染" },
    { id: "hair8", name: "雾霾蓝", icon: "💙", color: "#6a88b0", desc: "灰蓝染" },
    { id: "hair9", name: "薄荷绿", icon: "💚", color: "#6ab090", desc: "浅绿染" },
    { id: "hair10", name: "银灰白", icon: "🤍", color: "#c8c0c8", desc: "银白染" },
  ],
  top: [
    { id: "top1", name: "玫瑰蓬袖", icon: "👗", color: "#FF6B8A", desc: "公主舞会·甜" },
    { id: "top2", name: "奶油针织", icon: "🧶", color: "#FFE0EC", desc: "柔软毛衣·柔" },
    { id: "top3", name: "天蓝衬衫", icon: "👕", color: "#7eb8ff", desc: "清新衬衣·清" },
    { id: "top4", name: "薄荷绿衣", icon: "🌿", color: "#7ed9b0", desc: "夏日上衣·清" },
    { id: "top5", name: "薰衣草紫", icon: "💜", color: "#c8a8e8", desc: "柔美开衫·仙" },
    { id: "top6", name: "雪白蕾丝", icon: "🤍", color: "#fff8fc", desc: "蕾丝上衣·仙" },
    { id: "top7", name: "樱桃红卫衣", icon: "🍒", color: "#e8455a", desc: "街头卫衣·潮" },
    { id: "top8", name: "牛仔夹克", icon: "🧥", color: "#5a7aaa", desc: "牛仔外套·酷" },
    { id: "top9", name: "黑丝绒", icon: "🖤", color: "#2a2430", desc: "晚宴丝绒·雅" },
    { id: "top10", name: "橙黄阳光", icon: "🧡", color: "#ffb347", desc: "活力T恤·甜" },
    { id: "top11", name: "海蓝条纹", icon: "🌊", color: "#4a9ad9", desc: "海军风·清" },
    { id: "top12", name: "蜜桃吊带", icon: "🍑", color: "#ffb0c4", desc: "夏日吊带·甜" },
    { id: "top13", name: "墨绿旗袍领", icon: "🎋", color: "#2d6a4f", desc: "中式改良·雅" },
    { id: "top14", name: "酒红晚装", icon: "🍷", color: "#8b1e3f", desc: "晚宴上衣·雅" },
    { id: "top15", name: "鹅黄衬衫", icon: "🌼", color: "#ffe566", desc: "明亮衬衣·甜" },
    { id: "top16", name: "灰粉学院", icon: "📚", color: "#d8b4c8", desc: "学院针织·清" },
    { id: "top17", name: "冰蓝运动", icon: "❄️", color: "#a8d8ff", desc: "运动卫衣·潮" },
    { id: "top18", name: "焦糖开衫", icon: "☕", color: "#c4895a", desc: "秋日开衫·柔" },
  ],
  bottom: [
    { id: "bot1", name: "玫瑰舞会裙", icon: "👗", color: "#FF6B8A", skirt: true, desc: "蓬蓬裙·甜" },
    { id: "bot2", name: "牛仔长裤", icon: "👖", color: "#4a6a9a", skirt: false, desc: "直筒裤·酷" },
    { id: "bot3", name: "奶白西裤", icon: "🤍", color: "#f0e8f0", skirt: false, desc: "休闲裤·雅" },
    { id: "bot4", name: "粉色短裙", icon: "🎀", color: "#ff9ec0", skirt: true, desc: "A字裙·甜" },
    { id: "bot5", name: "格纹百褶", icon: "🏫", color: "#c07090", skirt: true, desc: "学院裙·清" },
    { id: "bot6", name: "黑色长裤", icon: "🖤", color: "#3a3a48", skirt: false, desc: "修身裤·酷" },
    { id: "bot7", name: "天蓝长裙", icon: "💙", color: "#7eb8ff", skirt: true, desc: "飘逸裙·仙" },
    { id: "bot8", name: "薄荷绿裙", icon: "💚", color: "#7ed9b0", skirt: true, desc: "清新裙·清" },
    { id: "bot9", name: "紫色纱裙", icon: "💜", color: "#b794f6", skirt: true, desc: "仙气裙·仙" },
    { id: "bot10", name: "卡其工装裤", icon: "🧢", color: "#c4a574", skirt: false, desc: "工装裤·潮" },
    { id: "bot11", name: "酒红长裙", icon: "🍷", color: "#8b1e3f", skirt: true, desc: "晚宴裙·雅" },
    { id: "bot12", name: "白色短裤", icon: "🩳", color: "#f5f0f5", skirt: false, desc: "夏日短裤·清" },
    { id: "bot13", name: "黑纱半裙", icon: "🌑", color: "#2a2438", skirt: true, desc: "暗黑裙·酷" },
    { id: "bot14", name: "橙黄伞裙", icon: "🧡", color: "#ffb347", skirt: true, desc: "活力裙·甜" },
    { id: "bot15", name: "深蓝阔腿裤", icon: "🌊", color: "#2c5282", skirt: false, desc: "阔腿裤·雅" },
    { id: "bot16", name: "粉格子裙", icon: "🩷", color: "#f8a0c0", skirt: true, desc: "甜美裙·甜" },
    { id: "bot17", name: "银灰铅笔裤", icon: "🩶", color: "#9aa0b0", skirt: false, desc: "职场裤·雅" },
    { id: "bot18", name: "翠绿纱裙", icon: "🍀", color: "#38a169", skirt: true, desc: "森系裙·仙" },
  ],
  accessory: [
    { id: "acc1", name: "金皇冠套装", icon: "👑", crown: true, earrings: true, necklace: true, desc: "公主全套·甜" },
    { id: "acc2", name: "珍珠耳钉", icon: "💎", earrings: true, desc: "精致珍珠·雅" },
    { id: "acc3", name: "爱心项链", icon: "💖", necklace: true, desc: "心形吊坠·甜" },
    { id: "acc4", name: "素颜无饰", icon: "✨", desc: "清爽干净·清" },
    { id: "acc5", name: "仅金皇冠", icon: "👑", crown: true, desc: "小金冠·甜" },
    { id: "acc6", name: "皇冠+项链", icon: "👸", crown: true, necklace: true, desc: "半套公主·甜" },
    { id: "acc7", name: "圆框眼镜", icon: "👓", glasses: true, desc: "知性眼镜·雅" },
    { id: "acc8", name: "眼镜+耳钉", icon: "🤓", glasses: true, earrings: true, desc: "学霸风·清" },
    { id: "acc9", name: "侧边小花", icon: "🌸", flower: true, desc: "花朵发夹·甜" },
    { id: "acc10", name: "花+珍珠", icon: "🌺", flower: true, earrings: true, desc: "花仙风·仙" },
    { id: "acc11", name: "粉色贝雷", icon: "🎨", beret: true, color: "#ef6b8a", desc: "法式贝雷·潮" },
    { id: "acc12", name: "黑色贝雷", icon: "🎩", beret: true, color: "#2a2430", desc: "暗黑贝雷·酷" },
    { id: "acc13", name: "金色星夹", icon: "⭐", star: true, desc: "星星发饰·甜" },
    { id: "acc14", name: "星夹+耳钉", icon: "✨", star: true, earrings: true, desc: "闪闪发饰·仙" },
    { id: "acc15", name: "蝴蝶发夹", icon: "🦋", butterfly: true, desc: "蝴蝶结夹·仙" },
    { id: "acc16", name: "猫耳发箍", icon: "🐱", catEar: true, desc: "可爱猫耳·潮" },
    { id: "acc17", name: "猫耳+项链", icon: "😺", catEar: true, necklace: true, desc: "猫娘风·潮" },
    { id: "acc18", name: "贝雷+眼镜", icon: "🕶️", beret: true, glasses: true, color: "#5a7aaa", desc: "文艺风·雅" },
    { id: "acc19", name: "花+皇冠", icon: "💐", crown: true, flower: true, desc: "花冠公主·甜" },
    { id: "acc20", name: "全套闪耀", icon: "🌟", crown: true, earrings: true, necklace: true, star: true, desc: "华丽全开·甜" },
    { id: "acc21", name: "蝶+珍珠", icon: "💠", butterfly: true, earrings: true, desc: "轻盈蝶饰·仙" },
    { id: "acc22", name: "蓝贝雷帽", icon: "💙", beret: true, color: "#7eb8ff", desc: "清新贝雷·清" },
  ],
  hat: [
    { id: "hat0", name: "不戴帽子", icon: "✨", desc: "光头也好看" },
    { id: "hatCrown", name: "金皇冠", icon: "👑", kind: "crown", desc: "戴在头顶" },
    { id: "hatBeretP", name: "粉贝雷帽", icon: "🎨", kind: "beret", color: "#ef6b8a", desc: "斜戴头顶" },
    { id: "hatBeretB", name: "黑贝雷帽", icon: "🎩", kind: "beret", color: "#2a2430", desc: "斜戴头顶" },
    { id: "hatBeretL", name: "蓝贝雷帽", icon: "💙", kind: "beret", color: "#7eb8ff", desc: "斜戴头顶" },
    { id: "hatCap", name: "粉棒球帽", icon: "🧢", kind: "cap", color: "#ff8ab0", desc: "鸭舌朝前" },
    { id: "hatCat", name: "猫耳发箍", icon: "🐱", kind: "catEar", desc: "戴在头顶" },
    { id: "hatFlower", name: "花环", icon: "🌸", kind: "flower", desc: "环绕头顶" },
    { id: "hatStar", name: "星星发夹", icon: "⭐", kind: "star", desc: "夹在发侧" },
    { id: "hatButterfly", name: "蝴蝶发夹", icon: "🦋", kind: "butterfly", desc: "夹在发侧" },
  ],
  jewelry: [
    { id: "jew0", name: "不戴首饰", icon: "✨", desc: "素颜清爽" },
    { id: "jewEarring", name: "珍珠耳环", icon: "💎", earrings: true, desc: "挂在耳垂" },
    { id: "jewNecklace", name: "爱心项链", icon: "💖", necklace: true, desc: "戴在脖子" },
    { id: "jewWatch", name: "粉红手表", icon: "⌚", watch: true, color: "#ff6b8a", desc: "戴在手腕" },
    { id: "jewBracelet", name: "金手链", icon: "📿", bracelet: true, color: "#FFC94A", desc: "戴在手腕" },
    { id: "jewGlasses", name: "圆框眼镜", icon: "👓", glasses: true, desc: "戴在鼻梁" },
    { id: "jewPearlSet", name: "耳饰+项链", icon: "💍", earrings: true, necklace: true, desc: "耳与颈" },
    { id: "jewFull", name: "华丽全套", icon: "🌟", earrings: true, necklace: true, watch: true, desc: "耳颈腕齐全" },
    { id: "jewStudy", name: "眼镜+耳钉", icon: "🤓", glasses: true, earrings: true, desc: "学霸风" },
  ],
  baby: [
    { id: "baby0", name: "不抱宝宝", icon: "✨", desc: "空手" },
    { id: "babyGirl", name: "粉裙宝宝", icon: "👶", kind: "baby", color: "#ffb0c8", wrap: "#ffe0ec", desc: "抱在怀里" },
    { id: "babyBoy", name: "蓝衣宝宝", icon: "🍼", kind: "baby", color: "#7ec8ff", wrap: "#d8eef8", desc: "抱在怀里" },
    { id: "babyBear", name: "小熊宝宝", icon: "🧸", kind: "babyBear", color: "#C89878", desc: "抱在怀里" },
    { id: "babyBunny", name: "兔兔宝宝", icon: "🐰", kind: "babyBunny", color: "#f5f0f5", desc: "抱在怀里" },
  ],
  prop: [
    { id: "prop0", name: "空手", icon: "🖐️", prop: "none", slot: "none", desc: "不拿道具" },
    { id: "prop1", name: "魔法棒", icon: "🪄", prop: "wand", slot: "hand", color: "#FFC94A", desc: "握在右手" },
    { id: "prop2", name: "薰衣草花束", icon: "💐", prop: "bouquet", slot: "arm", color: "#B89BE8", desc: "挽在臂弯" },
    { id: "prop3", name: "爱心气球", icon: "🎈", prop: "balloon", slot: "hand", color: "#FF6B8A", desc: "提在手里" },
    { id: "prop4", name: "小熊玩偶", icon: "🧸", prop: "teddy", slot: "arm", color: "#C89878", desc: "抱在臂弯" },
    { id: "prop5", name: "阳伞", icon: "☂️", prop: "parasol", slot: "hand", color: "#FF9EC0", desc: "撑在肩侧" },
    { id: "prop6", name: "生日蛋糕", icon: "🎂", prop: "cake", slot: "hand", color: "#FFE0EC", desc: "捧在手里" },
    { id: "prop7", name: "手提包", icon: "👜", prop: "bag", slot: "arm", color: "#7EC8FF", desc: "挂在小胳膊" },
    { id: "prop8", name: "仙女灯", icon: "🏮", prop: "lantern", slot: "hand", color: "#FFC94A", desc: "提在手里" },
    { id: "prop9", name: "棒棒糖", icon: "🍭", prop: "lollipop", slot: "hand", color: "#FF6B8A", desc: "握在手里" },
    { id: "prop10", name: "小提琴", icon: "🎻", prop: "violin", slot: "arm", color: "#8B5A3C", desc: "夹在臂侧" },
    { id: "prop11", name: "书本", icon: "📖", prop: "book", slot: "hand", color: "#5A7AB0", desc: "捧在手里" },
  ],
  bg: [
    { id: "bgRose", name: "玫瑰蜜糖", icon: "🌹", css: "bg-rose", desc: "粉玫瑰厅" },
    { id: "bgSky", name: "天空蓝", icon: "☁️", css: "bg-sky", desc: "晴空教室" },
    { id: "bgLavender", name: "薰衣草紫", icon: "💜", css: "bg-lavender", desc: "梦幻紫幕" },
    { id: "bgMint", name: "薄荷绿", icon: "🌿", css: "bg-mint", desc: "清新花园" },
    { id: "bgSunset", name: "日落橙", icon: "🌅", css: "bg-sunset", desc: "暖橙黄昏" },
    { id: "bgStar", name: "星空夜", icon: "✨", css: "bg-star", desc: "闪亮星空" },
    { id: "bgCream", name: "奶油白", icon: "🧁", css: "bg-cream", desc: "柔光奶油" },
    { id: "bgCherry", name: "樱花季", icon: "🌸", css: "bg-cherry", desc: "粉樱飘落" },
  ],
};

/** 多风格角色预设（化妆屋可切换） */
export const CHAR_STYLES = [
  {
    id: "princess",
    name: "小公主",
    icon: "👑",
    desc: "皇冠舞会裙",
    makeup: {
      lipstick: "lip1",
      blush: "blush1",
      eyeshadow: "eye1",
      faceShape: "faceRound",
      features: "featSweet",
      hairstyle: "hsTwin",
      hair: "hair1",
      top: "top1",
      bottom: "bot1",
      hat: "hatCrown",
      jewelry: "jewPearlSet",
      baby: "baby0",
      prop: "prop1",
      bg: "bgRose",
      accessory: "acc1",
    },
  },
  {
    id: "school",
    name: "学院风",
    icon: "📚",
    desc: "眼镜百褶裙",
    makeup: {
      lipstick: "lip6",
      blush: "blush3",
      eyeshadow: "eye3",
      faceShape: "faceOval",
      features: "featGentle",
      hairstyle: "hsBob",
      hair: "hair3",
      top: "top16",
      bottom: "bot5",
      hat: "hat0",
      jewelry: "jewStudy",
      baby: "baby0",
      prop: "prop11",
      bg: "bgSky",
      accessory: "acc8",
    },
  },
  {
    id: "fairy",
    name: "小仙女",
    icon: "🧚",
    desc: "银发纱裙",
    makeup: {
      lipstick: "lip5",
      blush: "blush4",
      eyeshadow: "eye2",
      faceShape: "faceHeart",
      features: "featShy",
      hairstyle: "hsWave",
      hair: "hair10",
      top: "top5",
      bottom: "bot9",
      hat: "hatButterfly",
      jewelry: "jewNecklace",
      baby: "baby0",
      prop: "prop2",
      bg: "bgLavender",
      accessory: "acc15",
    },
  },
  {
    id: "cool",
    name: "酷女孩",
    icon: "😎",
    desc: "牛仔街头",
    makeup: {
      lipstick: "lip2",
      blush: "blush6",
      eyeshadow: "eye5",
      faceShape: "faceLong",
      features: "featCool",
      hairstyle: "hsPony",
      hair: "hair2",
      top: "top8",
      bottom: "bot2",
      hat: "hatBeretB",
      jewelry: "jewWatch",
      baby: "baby0",
      prop: "prop7",
      bg: "bgStar",
      accessory: "acc12",
    },
  },
  {
    id: "cat",
    name: "甜心猫",
    icon: "🐱",
    desc: "猫耳可爱风",
    makeup: {
      lipstick: "lip4",
      blush: "blush4",
      eyeshadow: "eye1",
      faceShape: "faceSoft",
      features: "featLively",
      hairstyle: "hsTwin",
      hair: "hair7",
      top: "top12",
      bottom: "bot4",
      hat: "hatCat",
      jewelry: "jewEarring",
      baby: "babyBunny",
      prop: "prop0",
      bg: "bgCherry",
      accessory: "acc16",
    },
  },
  {
    id: "sporty",
    name: "活力少女",
    icon: "⚽",
    desc: "运动清爽",
    makeup: {
      lipstick: "lip6",
      blush: "blush5",
      eyeshadow: "eye6",
      faceShape: "faceRound",
      features: "featLively",
      hairstyle: "hsBun",
      hair: "hair6",
      top: "top17",
      bottom: "bot12",
      hat: "hatCap",
      jewelry: "jew0",
      baby: "baby0",
      prop: "prop9",
      bg: "bgMint",
      accessory: "acc4",
    },
  },
];

export const APPLIANCE_NAMES = {
  tv: "电视",
  ac: "空调",
  lamp: "落地灯",
  light: "吊灯",
  fridge: "冰箱",
  hood: "抽油烟机",
  microwave: "微波炉",
  stove: "燃气灶",
  rice: "电饭煲",
  oven: "烤箱",
  dishwasher: "洗碗机",
};
