export const SCENES = {
  makeup: { id: "makeup", title: "公主换装化妆屋" },
  market: { id: "market", title: "蜜糖超市" },
  home: { id: "home", title: "温馨客厅" },
  kitchen: { id: "kitchen", title: "家庭厨房" },
  dining: { id: "dining", title: "温馨餐厅" },
};

export const COLORS = {
  skin: 0xf2c4a0,
  hair: 0x5a3a28,
  floor: 0xe8d4c4,
  wall: 0xfff0f5,
  coral: 0xef6b8a,
  wood: 0xc48a5a,
  woodDark: 0x8a5a38,
  metal: 0xb0c0d0,
  white: 0xffffff,
  green: 0x6ecf7a,
};

export const MARKET_GOODS = {
  drinks: [
    { id: "juice", name: "果汁", icon: "果汁", price: 8, tag: "drink", color: "#ffb347" },
    { id: "milk", name: "牛奶", icon: "牛奶", price: 7, tag: "drink", color: "#f5f5f5" },
    { id: "soda", name: "汽水", icon: "汽水", price: 6, tag: "drink", color: "#7ec8ff" },
  ],
  veg: [
    { id: "tomato", name: "番茄", icon: "茄", price: 4, tag: "veg", color: "#ff6b5a" },
    { id: "carrot", name: "胡萝卜", icon: "萝", price: 3, tag: "veg", color: "#ff8f40" },
    { id: "broccoli", name: "西兰花", icon: "兰", price: 5, tag: "veg", color: "#4aaa50" },
    { id: "cabbage", name: "白菜", icon: "白", price: 3, tag: "veg", color: "#d8f0c8" },
  ],
  daily: [
    { id: "rice", name: "大米", icon: "米", price: 12, tag: "rice", color: "#f5f0e0" },
    { id: "oil", name: "食用油", icon: "油", price: 15, tag: "oil", color: "#f0d060" },
    { id: "flour", name: "面粉", icon: "粉", price: 8, tag: "flour", color: "#fff8e8" },
    { id: "egg", name: "鸡蛋", icon: "蛋", price: 6, tag: "egg", color: "#ffe8b0" },
  ],
  snack: [
    { id: "chips", name: "薯片", icon: "薯", price: 8, tag: "snack", color: "#ffe08a" },
    { id: "bread", name: "面包胚", icon: "包", price: 6, tag: "flour", color: "#e8c898" },
  ],
};

export const RECIPES = {
  stirfry: {
    name: "炒菜",
    need: ["veg", "oil"],
    needWashed: true,
    power: "stove",
    time: 2400,
    dish: "炒蔬菜",
    icon: "菜",
    vesselDefault: "plate",
  },
  rice: {
    name: "蒸米饭",
    need: ["rice"],
    power: "rice",
    time: 2800,
    dish: "米饭",
    icon: "饭",
    vesselDefault: "bowl",
  },
  porridge: {
    name: "煮粥",
    need: ["rice"],
    power: "stove",
    time: 2600,
    dish: "白粥",
    icon: "粥",
    vesselDefault: "bowl",
  },
  bread: {
    name: "烤面包",
    need: ["flour"],
    power: "oven",
    time: 3000,
    dish: "烤面包",
    icon: "包",
    vesselDefault: "plate",
  },
};

export const MAKEUP = {
  modes: [
    { id: "makeup", name: "化妆台" },
    { id: "dress", name: "换装间" },
  ],
  makeupTabs: [
    { id: "lipstick", name: "口红" },
    { id: "blush", name: "腮红" },
    { id: "eyeshadow", name: "眼影" },
    { id: "faceShape", name: "脸型" },
    { id: "features", name: "五官" },
  ],
  dressTabs: [
    { id: "hairstyle", name: "发型" },
    { id: "hair", name: "发色" },
    { id: "top", name: "上衣" },
    { id: "bottom", name: "下装" },
    { id: "accessory", name: "饰品" },
    { id: "prop", name: "大道具" },
  ],
  tabs: [
    { id: "lipstick", name: "口红" },
    { id: "blush", name: "腮红" },
    { id: "eyeshadow", name: "眼影" },
    { id: "faceShape", name: "脸型" },
    { id: "features", name: "五官" },
    { id: "hairstyle", name: "发型" },
    { id: "hair", name: "发色" },
    { id: "top", name: "上衣" },
    { id: "bottom", name: "下装" },
    { id: "accessory", name: "饰品" },
    { id: "prop", name: "大道具" },
  ],
  faceShape: [
    { id: "faceRound", name: "圆脸", icon: "⭕", shape: "round", rx: 92, ry: 92, desc: "可爱圆脸" },
    { id: "faceOval", name: "鹅蛋脸", icon: "🥚", shape: "oval", rx: 82, ry: 98, desc: "经典鹅蛋" },
    { id: "faceHeart", name: "心形脸", icon: "💗", shape: "heart", rx: 88, ry: 94, desc: "上宽下尖" },
    { id: "faceSoft", name: "柔和脸", icon: "☁️", shape: "soft", rx: 90, ry: 88, desc: "软萌短脸" },
    { id: "faceLong", name: "瓜子脸", icon: "🌙", shape: "long", rx: 76, ry: 102, desc: "清秀瓜子" },
  ],
  features: [
    { id: "featSweet", name: "甜笑", icon: "😊", look: "sweet", eyeScale: 1, desc: "弯弯笑眼" },
    { id: "featCool", name: "酷感", icon: "😎", look: "cool", eyeScale: 0.92, desc: "细长眼型" },
    { id: "featShy", name: "害羞", icon: "🥺", look: "shy", eyeScale: 1.05, desc: "水汪汪" },
    { id: "featLively", name: "元气", icon: "😆", look: "lively", eyeScale: 1.08, desc: "大笑露齿" },
    { id: "featGentle", name: "温柔", icon: "😌", look: "gentle", eyeScale: 0.98, desc: "浅笑温柔" },
  ],
  hairstyle: [
    { id: "hsTwin", name: "双马尾", icon: "🎀", style: "twin", desc: "活泼双马尾" },
    { id: "hsPony", name: "高马尾", icon: "🏇", style: "pony", desc: "利落马尾" },
    { id: "hsBob", name: "齐肩短发", icon: "💇", style: "bob", desc: "清爽短发" },
    { id: "hsLong", name: "长直发", icon: "👩", style: "long", desc: "飘逸长发" },
    { id: "hsBun", name: "丸子头", icon: "🍡", style: "bun", desc: "可爱丸子" },
    { id: "hsWave", name: "大波浪", icon: "🌊", style: "wave", desc: "卷卷波浪" },
  ],
  lipstick: [
    { id: "lip1", name: "蜜桃嘟嘟", icon: "💄", color: "#FF7FA3", desc: "水润唇膏" },
    { id: "lip2", name: "樱桃甜心", icon: "💋", color: "#d4455a", desc: "丝绒口红" },
    { id: "lip3", name: "豆沙奶茶", icon: "🧋", color: "#b06070", desc: "哑光唇泥" },
    { id: "lip4", name: "珊瑚橘", icon: "🍊", color: "#ff7a5c", desc: "亮泽唇彩" },
    { id: "lip5", name: "玫瑰雾", icon: "🌹", color: "#c45a78", desc: "雾面唇釉" },
    { id: "lip6", name: "裸粉", icon: "🎀", color: "#e8a0b0", desc: "日常淡唇" },
    { id: "lip7", name: "正红色", icon: "❤️", color: "#e11d48", desc: "经典口红" },
    { id: "lip8", name: "葡萄紫", icon: "🍇", color: "#7c3a6a", desc: "复古唇膏" },
  ],
  blush: [
    { id: "blush1", name: "蜜桃腮红", icon: "🍑", color: "#FF8AA8", desc: "粉饼" },
    { id: "blush2", name: "珊瑚蜜", icon: "🪸", color: "#ff8a9a", desc: "液体腮红" },
    { id: "blush3", name: "自然好气色", icon: "☀️", color: "#f0a090", desc: "修容盘" },
    { id: "blush4", name: "草莓冰", icon: "🍓", color: "#ff6b8a", desc: "奶油腮红" },
    { id: "blush5", name: "杏子奶", icon: "🧁", color: "#f0b898", desc: "柔光粉" },
    { id: "blush6", name: "梅子色", icon: "💜", color: "#c08098", desc: "高级腮红" },
  ],
  eyeshadow: [
    { id: "eye1", name: "粉棕盘", icon: "👁️", color: "#FF9EC0", desc: "四色眼影" },
    { id: "eye2", name: "玫瑰盘", icon: "🌺", color: "#d07090", desc: "珠光眼影" },
    { id: "eye3", name: "大地盘", icon: "🍂", color: "#a87858", desc: "哑光眼影" },
    { id: "eye4", name: "香槟金", icon: "✨", color: "#e8c898", desc: "闪片眼影" },
    { id: "eye5", name: "莓果紫", icon: "💜", color: "#9a6a9a", desc: "烟熏眼影" },
    { id: "eye6", name: "海蓝石", icon: "💙", color: "#6a9ac8", desc: "冷调眼影" },
  ],
  hair: [
    { id: "hair1", name: "栗棕日常", icon: "👧", color: "#6B3F2A", desc: "自然棕" },
    { id: "hair2", name: "深褐夜色", icon: "💇", color: "#3a2820", desc: "深色染" },
    { id: "hair3", name: "蜜茶金", icon: "🍵", color: "#8a5a38", desc: "浅棕染" },
    { id: "hair4", name: "红酒棕", icon: "🍷", color: "#6a3040", desc: "酒红染" },
    { id: "hair5", name: "巧克力", icon: "🍫", color: "#4a3020", desc: "暖棕染" },
    { id: "hair6", name: "亚麻浅棕", icon: "🌾", color: "#a07850", desc: "日系染" },
    { id: "hair7", name: "樱花粉", icon: "🌸", color: "#e8a0b8", desc: "粉色染" },
    { id: "hair8", name: "雾霾蓝", icon: "💙", color: "#6a88b0", desc: "灰蓝染" },
    { id: "hair9", name: "薄荷绿", icon: "💚", color: "#6ab090", desc: "浅绿染" },
    { id: "hair10", name: "银灰白", icon: "🤍", color: "#c8c0c8", desc: "银白染" },
  ],
  top: [
    { id: "top1", name: "玫瑰蓬袖", icon: "👗", color: "#FF6B8A", desc: "公主舞会·甜" },
    { id: "top2", name: "奶油针织", icon: "🧶", color: "#FFE0EC", desc: "柔软毛衣·柔" },
    { id: "top3", name: "天蓝衬衫", icon: "👕", color: "#7eb8ff", desc: "清新衬衣·清" },
    { id: "top4", name: "薄荷绿衣", icon: "🌿", color: "#7ed9b0", desc: "夏日上衣·清" },
    { id: "top5", name: "薰衣草紫", icon: "💜", color: "#c8a8e8", desc: "柔美开衫·仙" },
    { id: "top6", name: "雪白蕾丝", icon: "🤍", color: "#fff8fc", desc: "蕾丝上衣·仙" },
    { id: "top7", name: "樱桃红卫衣", icon: "🍒", color: "#e8455a", desc: "街头卫衣·潮" },
    { id: "top8", name: "牛仔夹克", icon: "🧥", color: "#5a7aaa", desc: "牛仔外套·酷" },
    { id: "top9", name: "黑丝绒", icon: "🖤", color: "#2a2430", desc: "晚宴丝绒·雅" },
    { id: "top10", name: "橙黄阳光", icon: "🧡", color: "#ffb347", desc: "活力T恤·甜" },
    { id: "top11", name: "海蓝条纹", icon: "🌊", color: "#4a9ad9", desc: "海军风·清" },
    { id: "top12", name: "蜜桃吊带", icon: "🍑", color: "#ffb0c4", desc: "夏日吊带·甜" },
    { id: "top13", name: "墨绿旗袍领", icon: "🎋", color: "#2d6a4f", desc: "中式改良·雅" },
    { id: "top14", name: "酒红晚装", icon: "🍷", color: "#8b1e3f", desc: "晚宴上衣·雅" },
    { id: "top15", name: "鹅黄衬衫", icon: "🌼", color: "#ffe566", desc: "明亮衬衣·甜" },
    { id: "top16", name: "灰粉学院", icon: "📚", color: "#d8b4c8", desc: "学院针织·清" },
    { id: "top17", name: "冰蓝运动", icon: "❄️", color: "#a8d8ff", desc: "运动卫衣·潮" },
    { id: "top18", name: "焦糖开衫", icon: "☕", color: "#c4895a", desc: "秋日开衫·柔" },
  ],
  bottom: [
    { id: "bot1", name: "玫瑰舞会裙", icon: "👗", color: "#FF6B8A", skirt: true, desc: "蓬蓬裙·甜" },
    { id: "bot2", name: "牛仔长裤", icon: "👖", color: "#4a6a9a", skirt: false, desc: "直筒裤·酷" },
    { id: "bot3", name: "奶白西裤", icon: "🤍", color: "#f0e8f0", skirt: false, desc: "休闲裤·雅" },
    { id: "bot4", name: "粉色短裙", icon: "🎀", color: "#ff9ec0", skirt: true, desc: "A字裙·甜" },
    { id: "bot5", name: "格纹百褶", icon: "🏫", color: "#c07090", skirt: true, desc: "学院裙·清" },
    { id: "bot6", name: "黑色长裤", icon: "🖤", color: "#3a3a48", skirt: false, desc: "修身裤·酷" },
    { id: "bot7", name: "天蓝长裙", icon: "💙", color: "#7eb8ff", skirt: true, desc: "飘逸裙·仙" },
    { id: "bot8", name: "薄荷绿裙", icon: "💚", color: "#7ed9b0", skirt: true, desc: "清新裙·清" },
    { id: "bot9", name: "紫色纱裙", icon: "💜", color: "#b794f6", skirt: true, desc: "仙气裙·仙" },
    { id: "bot10", name: "卡其工装裤", icon: "🧢", color: "#c4a574", skirt: false, desc: "工装裤·潮" },
    { id: "bot11", name: "酒红长裙", icon: "🍷", color: "#8b1e3f", skirt: true, desc: "晚宴裙·雅" },
    { id: "bot12", name: "白色短裤", icon: "🩳", color: "#f5f0f5", skirt: false, desc: "夏日短裤·清" },
    { id: "bot13", name: "黑纱半裙", icon: "🌑", color: "#2a2438", skirt: true, desc: "暗黑裙·酷" },
    { id: "bot14", name: "橙黄伞裙", icon: "🧡", color: "#ffb347", skirt: true, desc: "活力裙·甜" },
    { id: "bot15", name: "深蓝阔腿裤", icon: "🌊", color: "#2c5282", skirt: false, desc: "阔腿裤·雅" },
    { id: "bot16", name: "粉格子裙", icon: "🩷", color: "#f8a0c0", skirt: true, desc: "甜美裙·甜" },
    { id: "bot17", name: "银灰铅笔裤", icon: "🩶", color: "#9aa0b0", skirt: false, desc: "职场裤·雅" },
    { id: "bot18", name: "翠绿纱裙", icon: "🍀", color: "#38a169", skirt: true, desc: "森系裙·仙" },
  ],
  accessory: [
    { id: "acc1", name: "金皇冠套装", icon: "👑", crown: true, earrings: true, necklace: true, desc: "公主全套·甜" },
    { id: "acc2", name: "珍珠耳钉", icon: "💎", earrings: true, desc: "精致珍珠·雅" },
    { id: "acc3", name: "爱心项链", icon: "💖", necklace: true, desc: "心形吊坠·甜" },
    { id: "acc4", name: "素颜无饰", icon: "✨", desc: "清爽干净·清" },
    { id: "acc5", name: "仅金皇冠", icon: "👑", crown: true, desc: "小金冠·甜" },
    { id: "acc6", name: "皇冠+项链", icon: "👸", crown: true, necklace: true, desc: "半套公主·甜" },
    { id: "acc7", name: "圆框眼镜", icon: "👓", glasses: true, desc: "知性眼镜·雅" },
    { id: "acc8", name: "眼镜+耳钉", icon: "🤓", glasses: true, earrings: true, desc: "学霸风·清" },
    { id: "acc9", name: "侧边小花", icon: "🌸", flower: true, desc: "花朵发夹·甜" },
    { id: "acc10", name: "花+珍珠", icon: "🌺", flower: true, earrings: true, desc: "花仙风·仙" },
    { id: "acc11", name: "粉色贝雷", icon: "🎨", beret: true, color: "#ef6b8a", desc: "法式贝雷·潮" },
    { id: "acc12", name: "黑色贝雷", icon: "🎩", beret: true, color: "#2a2430", desc: "暗黑贝雷·酷" },
    { id: "acc13", name: "金色星夹", icon: "⭐", star: true, desc: "星星发饰·甜" },
    { id: "acc14", name: "星夹+耳钉", icon: "✨", star: true, earrings: true, desc: "闪闪发饰·仙" },
    { id: "acc15", name: "蝴蝶发夹", icon: "🦋", butterfly: true, desc: "蝴蝶结夹·仙" },
    { id: "acc16", name: "猫耳发箍", icon: "🐱", catEar: true, desc: "可爱猫耳·潮" },
    { id: "acc17", name: "猫耳+项链", icon: "😺", catEar: true, necklace: true, desc: "猫娘风·潮" },
    { id: "acc18", name: "贝雷+眼镜", icon: "🕶️", beret: true, glasses: true, color: "#5a7aaa", desc: "文艺风·雅" },
    { id: "acc19", name: "花+皇冠", icon: "💐", crown: true, flower: true, desc: "花冠公主·甜" },
    { id: "acc20", name: "全套闪耀", icon: "🌟", crown: true, earrings: true, necklace: true, star: true, desc: "华丽全开·甜" },
    { id: "acc21", name: "蝶+珍珠", icon: "💠", butterfly: true, earrings: true, desc: "轻盈蝶饰·仙" },
    { id: "acc22", name: "蓝贝雷帽", icon: "💙", beret: true, color: "#7eb8ff", desc: "清新贝雷·清" },
  ],
  prop: [
    { id: "prop0", name: "空手", icon: "🖐️", prop: "none", desc: "不拿道具" },
    { id: "prop1", name: "魔法棒", icon: "🪄", prop: "wand", color: "#FFC94A", desc: "星星魔法棒" },
    { id: "prop2", name: "薰衣草花束", icon: "💐", prop: "bouquet", color: "#B89BE8", desc: "大捧鲜花" },
    { id: "prop3", name: "爱心气球", icon: "🎈", prop: "balloon", color: "#FF6B8A", desc: "粉心气球" },
    { id: "prop4", name: "小熊玩偶", icon: "🧸", prop: "teddy", color: "#C89878", desc: "抱抱熊" },
    { id: "prop5", name: "阳伞", icon: "☂️", prop: "parasol", color: "#FF9EC0", desc: "蕾丝阳伞" },
    { id: "prop6", name: "生日蛋糕", icon: "🎂", prop: "cake", color: "#FFE0EC", desc: "多层蛋糕" },
    { id: "prop7", name: "购物袋", icon: "🛍️", prop: "bag", color: "#7EC8FF", desc: "大购物袋" },
    { id: "prop8", name: "仙女灯", icon: "🏮", prop: "lantern", color: "#FFC94A", desc: "发光提灯" },
    { id: "prop9", name: "棒棒糖", icon: "🍭", prop: "lollipop", color: "#FF6B8A", desc: "超大棒棒糖" },
    { id: "prop10", name: "小提琴", icon: "🎻", prop: "violin", color: "#8B5A3C", desc: "音乐会" },
    { id: "prop11", name: "书本", icon: "📖", prop: "book", color: "#5A7AB0", desc: "厚书" },
  ],
};

/** 多风格角色预设（化妆屋可切换） */
export const CHAR_STYLES = [
  {
    id: "princess",
    name: "小公主",
    icon: "👑",
    desc: "皇冠舞会裙",
    makeup: {
      lipstick: "lip1",
      blush: "blush1",
      eyeshadow: "eye1",
      faceShape: "faceRound",
      features: "featSweet",
      hairstyle: "hsTwin",
      hair: "hair1",
      top: "top1",
      bottom: "bot1",
      accessory: "acc1",
      prop: "prop1",
    },
  },
  {
    id: "school",
    name: "学院风",
    icon: "📚",
    desc: "眼镜百褶裙",
    makeup: {
      lipstick: "lip6",
      blush: "blush3",
      eyeshadow: "eye3",
      faceShape: "faceOval",
      features: "featGentle",
      hairstyle: "hsBob",
      hair: "hair3",
      top: "top16",
      bottom: "bot5",
      accessory: "acc8",
      prop: "prop11",
    },
  },
  {
    id: "fairy",
    name: "小仙女",
    icon: "🧚",
    desc: "银发纱裙",
    makeup: {
      lipstick: "lip5",
      blush: "blush4",
      eyeshadow: "eye2",
      faceShape: "faceHeart",
      features: "featShy",
      hairstyle: "hsWave",
      hair: "hair10",
      top: "top5",
      bottom: "bot9",
      accessory: "acc15",
      prop: "prop2",
    },
  },
  {
    id: "cool",
    name: "酷女孩",
    icon: "😎",
    desc: "牛仔街头",
    makeup: {
      lipstick: "lip2",
      blush: "blush6",
      eyeshadow: "eye5",
      faceShape: "faceLong",
      features: "featCool",
      hairstyle: "hsPony",
      hair: "hair2",
      top: "top8",
      bottom: "bot2",
      accessory: "acc12",
      prop: "prop7",
    },
  },
  {
    id: "cat",
    name: "甜心猫",
    icon: "🐱",
    desc: "猫耳可爱风",
    makeup: {
      lipstick: "lip4",
      blush: "blush4",
      eyeshadow: "eye1",
      faceShape: "faceSoft",
      features: "featLively",
      hairstyle: "hsTwin",
      hair: "hair7",
      top: "top12",
      bottom: "bot4",
      accessory: "acc16",
      prop: "prop4",
    },
  },
  {
    id: "sporty",
    name: "活力少女",
    icon: "⚽",
    desc: "运动清爽",
    makeup: {
      lipstick: "lip6",
      blush: "blush5",
      eyeshadow: "eye6",
      faceShape: "faceRound",
      features: "featLively",
      hairstyle: "hsBun",
      hair: "hair6",
      top: "top17",
      bottom: "bot12",
      accessory: "acc4",
      prop: "prop9",
    },
  },
];

export const APPLIANCE_NAMES = {
  tv: "电视",
  ac: "空调",
  lamp: "落地灯",
  light: "吊灯",
  fridge: "冰箱",
  hood: "抽油烟机",
  microwave: "微波炉",
  stove: "燃气灶",
  rice: "电饭煲",
  oven: "烤箱",
  dishwasher: "洗碗机",
};
